# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  host: db

  development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
 <<: *default
 adapter: postgresql
 encoding: unicode
 pool: 5
